// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browser_sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrowserSession = `-- name: CreateBrowserSession :one
INSERT INTO browser_sessions (digest, token_id, expires_at)
SELECT $1::bytea, t.id,
       LEAST(statement_timestamp() + interval '168 hours', t.expires_at)
FROM api_tokens AS t
JOIN identities AS i ON i.id = t.identity_id
WHERE t.digest = $2
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > statement_timestamp())
  AND i.enabled = true
RETURNING expires_at
`

type CreateBrowserSessionParams struct {
	SessionDigest []byte `db:"session_digest"`
	TokenDigest   []byte `db:"token_digest"`
}

func (q *Queries) CreateBrowserSession(ctx context.Context, arg CreateBrowserSessionParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, createBrowserSession, arg.SessionDigest, arg.TokenDigest)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const deleteBrowserSession = `-- name: DeleteBrowserSession :exec
DELETE FROM browser_sessions WHERE digest = $1
`

func (q *Queries) DeleteBrowserSession(ctx context.Context, digest []byte) error {
	_, err := q.db.Exec(ctx, deleteBrowserSession, digest)
	return err
}

const deleteExpiredBrowserSessions = `-- name: DeleteExpiredBrowserSessions :exec
DELETE FROM browser_sessions WHERE digest IN (
    SELECT digest FROM browser_sessions
    WHERE expires_at <= statement_timestamp()
    ORDER BY expires_at
    LIMIT 100
)
`

func (q *Queries) DeleteExpiredBrowserSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredBrowserSessions)
	return err
}
