// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: browse.sql

package database

import (
	"context"
)

const browseHasPending = `-- name: BrowseHasPending :one
SELECT EXISTS(SELECT 1 FROM browse_changes WHERE zone = $1::uuid AND NOT processed)
`

func (q *Queries) BrowseHasPending(ctx context.Context, zone string) (bool, error) {
	row := q.db.QueryRow(ctx, browseHasPending, zone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBrowseZone = `-- name: GetBrowseZone :one
SELECT id, upstream, zone_id, generation, revision, cursor_key, last_viewed_at, refreshed_at, error, full_requested, full_lease, full_lease_until, full_started_at, retry_at FROM browse_zones WHERE upstream = $1::text AND zone_id = $2::text
`

type GetBrowseZoneParams struct {
	Upstream string `db:"upstream"`
	ZoneID   string `db:"zone_id"`
}

func (q *Queries) GetBrowseZone(ctx context.Context, arg GetBrowseZoneParams) (BrowseZone, error) {
	row := q.db.QueryRow(ctx, getBrowseZone, arg.Upstream, arg.ZoneID)
	var i BrowseZone
	err := row.Scan(
		&i.ID,
		&i.Upstream,
		&i.ZoneID,
		&i.Generation,
		&i.Revision,
		&i.CursorKey,
		&i.LastViewedAt,
		&i.RefreshedAt,
		&i.Error,
		&i.FullRequested,
		&i.FullLease,
		&i.FullLeaseUntil,
		&i.FullStartedAt,
		&i.RetryAt,
	)
	return i, err
}

const listBrowseRRsets = `-- name: ListBrowseRRsets :many
SELECT name, type, payload FROM browse_rrsets
WHERE zone = $1::uuid AND generation = $2::uuid
AND name >= $3::text AND name <= $4::text
AND (name, type) > ($5::text, $6::text)
ORDER BY name, type LIMIT 101
`

type ListBrowseRRsetsParams struct {
	Zone        string `db:"zone"`
	Generation  string `db:"generation"`
	NameFrom    string `db:"name_from"`
	NameThrough string `db:"name_through"`
	AfterName   string `db:"after_name"`
	AfterType   string `db:"after_type"`
}

type ListBrowseRRsetsRow struct {
	Name    string `db:"name"`
	Type    string `db:"type"`
	Payload []byte `db:"payload"`
}

func (q *Queries) ListBrowseRRsets(ctx context.Context, arg ListBrowseRRsetsParams) ([]ListBrowseRRsetsRow, error) {
	rows, err := q.db.Query(ctx, listBrowseRRsets,
		arg.Zone,
		arg.Generation,
		arg.NameFrom,
		arg.NameThrough,
		arg.AfterName,
		arg.AfterType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrowseRRsetsRow{}
	for rows.Next() {
		var i ListBrowseRRsetsRow
		if err := rows.Scan(&i.Name, &i.Type, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrowseRRsetsByType = `-- name: ListBrowseRRsetsByType :many
SELECT name, type, payload FROM browse_rrsets
WHERE zone = $1::uuid AND generation = $2::uuid AND type = $3::text
AND name >= $4::text AND name <= $5::text
AND (name, type) > ($6::text, $7::text)
ORDER BY name, type LIMIT 101
`

type ListBrowseRRsetsByTypeParams struct {
	Zone        string `db:"zone"`
	Generation  string `db:"generation"`
	Type        string `db:"type"`
	NameFrom    string `db:"name_from"`
	NameThrough string `db:"name_through"`
	AfterName   string `db:"after_name"`
	AfterType   string `db:"after_type"`
}

type ListBrowseRRsetsByTypeRow struct {
	Name    string `db:"name"`
	Type    string `db:"type"`
	Payload []byte `db:"payload"`
}

func (q *Queries) ListBrowseRRsetsByType(ctx context.Context, arg ListBrowseRRsetsByTypeParams) ([]ListBrowseRRsetsByTypeRow, error) {
	rows, err := q.db.Query(ctx, listBrowseRRsetsByType,
		arg.Zone,
		arg.Generation,
		arg.Type,
		arg.NameFrom,
		arg.NameThrough,
		arg.AfterName,
		arg.AfterType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBrowseRRsetsByTypeRow{}
	for rows.Next() {
		var i ListBrowseRRsetsByTypeRow
		if err := rows.Scan(&i.Name, &i.Type, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestBrowseRefresh = `-- name: RequestBrowseRefresh :exec
UPDATE browse_zones SET full_requested = true, retry_at = now()
WHERE id = $1::uuid AND full_lease IS NULL
`

func (q *Queries) RequestBrowseRefresh(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, requestBrowseRefresh, id)
	return err
}

const touchBrowseZone = `-- name: TouchBrowseZone :one
INSERT INTO browse_zones(id, upstream, zone_id, cursor_key)
VALUES ($1::uuid, $2::text, $3::text, $4::bytea)
ON CONFLICT (upstream, zone_id) DO UPDATE SET last_viewed_at = now()
RETURNING id, upstream, zone_id, generation, revision, cursor_key, last_viewed_at, refreshed_at, error, full_requested, full_lease, full_lease_until, full_started_at, retry_at
`

type TouchBrowseZoneParams struct {
	ID        string `db:"id"`
	Upstream  string `db:"upstream"`
	ZoneID    string `db:"zone_id"`
	CursorKey []byte `db:"cursor_key"`
}

func (q *Queries) TouchBrowseZone(ctx context.Context, arg TouchBrowseZoneParams) (BrowseZone, error) {
	row := q.db.QueryRow(ctx, touchBrowseZone,
		arg.ID,
		arg.Upstream,
		arg.ZoneID,
		arg.CursorKey,
	)
	var i BrowseZone
	err := row.Scan(
		&i.ID,
		&i.Upstream,
		&i.ZoneID,
		&i.Generation,
		&i.Revision,
		&i.CursorKey,
		&i.LastViewedAt,
		&i.RefreshedAt,
		&i.Error,
		&i.FullRequested,
		&i.FullLease,
		&i.FullLeaseUntil,
		&i.FullStartedAt,
		&i.RetryAt,
	)
	return i, err
}
