// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type APIToken struct {
	ID         string             `db:"id"`
	IdentityID string             `db:"identity_id"`
	Label      string             `db:"label"`
	Digest     []byte             `db:"digest"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
}

type AuditEvent struct {
	ID                   string             `db:"id"`
	OccurredAt           pgtype.Timestamptz `db:"occurred_at"`
	EventKind            string             `db:"event_kind"`
	OperationID          *string            `db:"operation_id"`
	IntentEventID        *string            `db:"intent_event_id"`
	IntentEventKind      *string            `db:"intent_event_kind"`
	RequestID            string             `db:"request_id"`
	ActorIdentityID      *string            `db:"actor_identity_id"`
	ActorTokenID         *string            `db:"actor_token_id"`
	Action               string             `db:"action"`
	TargetKind           string             `db:"target_kind"`
	TargetID             string             `db:"target_id"`
	Result               string             `db:"result"`
	RRsetSummary         []byte             `db:"rrset_summary"`
	MatchedDelegationIDs []string           `db:"matched_delegation_ids"`
	Details              []byte             `db:"details"`
	ResponseClass        *string            `db:"response_class"`
	ResponseCode         *int32             `db:"response_code"`
	RequestDigest        []byte             `db:"request_digest"`
	ResponseDigest       []byte             `db:"response_digest"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at"`
}

type BrowseChange struct {
	Zone       string             `db:"zone"`
	Operation  string             `db:"operation"`
	Name       string             `db:"name"`
	Type       string             `db:"type"`
	ReadyAt    pgtype.Timestamptz `db:"ready_at"`
	ChangedAt  pgtype.Timestamptz `db:"changed_at"`
	Processed  bool               `db:"processed"`
	Lease      *string            `db:"lease"`
	LeaseUntil pgtype.Timestamptz `db:"lease_until"`
}

type BrowseRrset struct {
	Zone       string `db:"zone"`
	Generation string `db:"generation"`
	Name       string `db:"name"`
	Type       string `db:"type"`
	Payload    []byte `db:"payload"`
}

type BrowseZone struct {
	ID             string             `db:"id"`
	Upstream       string             `db:"upstream"`
	ZoneID         string             `db:"zone_id"`
	Generation     *string            `db:"generation"`
	Revision       int64              `db:"revision"`
	CursorKey      []byte             `db:"cursor_key"`
	LastViewedAt   pgtype.Timestamptz `db:"last_viewed_at"`
	RefreshedAt    pgtype.Timestamptz `db:"refreshed_at"`
	Error          *string            `db:"error"`
	FullRequested  bool               `db:"full_requested"`
	FullLease      *string            `db:"full_lease"`
	FullLeaseUntil pgtype.Timestamptz `db:"full_lease_until"`
	FullStartedAt  pgtype.Timestamptz `db:"full_started_at"`
	RetryAt        pgtype.Timestamptz `db:"retry_at"`
}

type BrowserSession struct {
	Digest    []byte             `db:"digest"`
	TokenID   string             `db:"token_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at"`
}

type Delegation struct {
	ID                  string             `db:"id"`
	ZoneBindingID       string             `db:"zone_binding_id"`
	GranteeIdentityID   *string            `db:"grantee_identity_id"`
	GranteeGroupID      *string            `db:"grantee_group_id"`
	CreatedByIdentityID string             `db:"created_by_identity_id"`
	RevokedByIdentityID *string            `db:"revoked_by_identity_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	RevokedAt           pgtype.Timestamptz `db:"revoked_at"`
}

type DelegationChangeKind struct {
	DelegationID string `db:"delegation_id"`
	ChangeKind   string `db:"change_kind"`
}

type DelegationRecordType struct {
	DelegationID string `db:"delegation_id"`
	RecordType   string `db:"record_type"`
}

type DelegationSelector struct {
	DelegationID   string `db:"delegation_id"`
	Position       int16  `db:"position"`
	Kind           string `db:"kind"`
	Selector       string `db:"selector"`
	SQLLikePattern string `db:"sql_like_pattern"`
}

type Group struct {
	ID          string             `db:"id"`
	Handle      string             `db:"handle"`
	DisplayName *string            `db:"display_name"`
	Enabled     bool               `db:"enabled"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

type GroupMembership struct {
	GroupID           string             `db:"group_id"`
	IdentityID        string             `db:"identity_id"`
	AddedByIdentityID string             `db:"added_by_identity_id"`
	CreatedAt         pgtype.Timestamptz `db:"created_at"`
}

type Identity struct {
	ID          string             `db:"id"`
	Kind        string             `db:"kind"`
	Handle      string             `db:"handle"`
	DisplayName *string            `db:"display_name"`
	Enabled     bool               `db:"enabled"`
	IsOperator  bool               `db:"is_operator"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

type InstallationMetadata struct {
	Singleton          bool               `db:"singleton"`
	InstallationID     string             `db:"installation_id"`
	InitializedAt      pgtype.Timestamptz `db:"initialized_at"`
	RestoreRequired    bool               `db:"restore_required"`
	RestoreFinalizedAt pgtype.Timestamptz `db:"restore_finalized_at"`
}

type OperatorGuard struct {
	Singleton bool `db:"singleton"`
}

type ZoneBinding struct {
	ID                  string             `db:"id"`
	Generation          int64              `db:"generation"`
	Upstream            string             `db:"upstream"`
	PowerDNSZoneID      string             `db:"powerdns_zone_id"`
	ZoneName            string             `db:"zone_name"`
	CreatedByIdentityID string             `db:"created_by_identity_id"`
	RetiredByIdentityID *string            `db:"retired_by_identity_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	RetiredAt           pgtype.Timestamptz `db:"retired_at"`
}
