// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMembership = `-- name: AddGroupMembership :execrows
INSERT INTO group_memberships (group_id, identity_id, added_by_identity_id)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, identity_id) DO NOTHING
`

type AddGroupMembershipParams struct {
	GroupID           string `db:"group_id"`
	IdentityID        string `db:"identity_id"`
	AddedByIdentityID string `db:"added_by_identity_id"`
}

func (q *Queries) AddGroupMembership(ctx context.Context, arg AddGroupMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, addGroupMembership, arg.GroupID, arg.IdentityID, arg.AddedByIdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const authenticateToken = `-- name: AuthenticateToken :one
SELECT t.id AS token_id, i.id AS identity_id, i.kind, i.handle, i.is_operator
FROM api_tokens AS t
JOIN identities AS i ON i.id = t.identity_id
WHERE t.id IN (
    SELECT header_token.id FROM api_tokens AS header_token WHERE header_token.digest = $1 AND NOT $2::boolean
    UNION ALL
    SELECT session.token_id FROM browser_sessions AS session WHERE session.digest = $1 AND $2::boolean AND session.expires_at > statement_timestamp()
  )
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > statement_timestamp())
  AND i.enabled = true
`

type AuthenticateTokenParams struct {
	CredentialDigest []byte `db:"credential_digest"`
	IsSession        bool   `db:"is_session"`
}

type AuthenticateTokenRow struct {
	TokenID    string `db:"token_id"`
	IdentityID string `db:"identity_id"`
	Kind       string `db:"kind"`
	Handle     string `db:"handle"`
	IsOperator bool   `db:"is_operator"`
}

func (q *Queries) AuthenticateToken(ctx context.Context, arg AuthenticateTokenParams) (AuthenticateTokenRow, error) {
	row := q.db.QueryRow(ctx, authenticateToken, arg.CredentialDigest, arg.IsSession)
	var i AuthenticateTokenRow
	err := row.Scan(
		&i.TokenID,
		&i.IdentityID,
		&i.Kind,
		&i.Handle,
		&i.IsOperator,
	)
	return i, err
}

const authorizeRRsetBatch = `-- name: AuthorizeRRsetBatch :many
WITH authenticated AS (
    SELECT t.id AS token_id, i.id AS identity_id, i.kind, i.handle, i.is_operator
    FROM api_tokens AS t
    JOIN identities AS i ON i.id = t.identity_id
    WHERE t.id IN (
        SELECT header_token.id FROM api_tokens AS header_token WHERE header_token.digest = $1 AND NOT $2::boolean
        UNION ALL
        SELECT session.token_id FROM browser_sessions AS session WHERE session.digest = $1 AND $2::boolean AND session.expires_at > statement_timestamp()
      )
      AND t.revoked_at IS NULL
      AND (t.expires_at IS NULL OR t.expires_at > statement_timestamp())
      AND i.enabled = true
),
input_tuples AS (
    SELECT (item.ordinality - 1)::integer AS batch_index,
           item.value ->> 'owner' AS owner,
           item.value ->> 'record_type' AS record_type,
           item.value ->> 'change_kind' AS change_kind,
           (item.value ->> 'literal_wildcard')::boolean AS literal_wildcard
    FROM jsonb_array_elements($3::jsonb) WITH ORDINALITY AS item(value, ordinality)
),
active_binding AS (
    SELECT id, zone_name
    FROM zone_bindings
    WHERE upstream = $4
      AND powerdns_zone_id = $5
      AND retired_at IS NULL
)
SELECT COALESCE(a.token_id::text, '')::text AS token_id,
       COALESCE(a.identity_id::text, '')::text AS identity_id,
       COALESCE(a.kind, '') AS identity_kind,
       COALESCE(a.handle, '') AS identity_handle,
       COALESCE(a.is_operator, false) AS is_operator,
       COALESCE(b.id::text, '')::text AS zone_binding_id,
       t.batch_index, t.owner::text AS owner, t.record_type::text AS record_type,
       t.change_kind::text AS change_kind,
       (COALESCE(a.is_operator, false) OR count(DISTINCT d.id) > 0)::boolean AS allowed,
       COALESCE(
           array_agg(DISTINCT d.id) FILTER (WHERE d.id IS NOT NULL),
           '{}'::uuid[]
       )::uuid[] AS matched_delegation_ids
FROM input_tuples AS t
LEFT JOIN authenticated AS a ON true
LEFT JOIN active_binding AS b ON true
LEFT JOIN delegations AS d
  ON d.zone_binding_id = b.id
 AND d.revoked_at IS NULL
 AND (
      d.grantee_identity_id = a.identity_id
      OR (
          d.grantee_group_id IS NOT NULL
          AND EXISTS (
              SELECT 1
              FROM group_memberships AS membership
              JOIN groups AS member_group
                ON member_group.id = membership.group_id
               AND member_group.enabled = true
              WHERE membership.identity_id = a.identity_id
                AND membership.group_id = d.grantee_group_id
          )
      )
 )
 AND (
      b.zone_name = '.'
      OR t.owner = b.zone_name
      OR right(t.owner, length(b.zone_name) + 1) = '.' || b.zone_name
 )
 AND EXISTS (
      SELECT 1
      FROM delegation_selectors AS selector
      WHERE selector.delegation_id = d.id
        AND (
            (selector.kind = 'exact' AND selector.selector = t.owner)
            OR (
                selector.kind = 'glob'
                AND t.owner <> b.zone_name
                AND NOT t.literal_wildcard
                AND t.owner COLLATE "C" LIKE selector.sql_like_pattern COLLATE "C" ESCAPE '\'
            )
        )
 )
 AND (
      NOT EXISTS (
          SELECT 1 FROM delegation_record_types AS record_filter
          WHERE record_filter.delegation_id = d.id
      )
      OR EXISTS (
          SELECT 1 FROM delegation_record_types AS record_filter
          WHERE record_filter.delegation_id = d.id
            AND record_filter.record_type = t.record_type
      )
 )
 AND (
      NOT EXISTS (
          SELECT 1 FROM delegation_change_kinds AS change_filter
          WHERE change_filter.delegation_id = d.id
      )
      OR EXISTS (
          SELECT 1 FROM delegation_change_kinds AS change_filter
          WHERE change_filter.delegation_id = d.id
            AND change_filter.change_kind = t.change_kind
      )
 )
GROUP BY a.token_id, a.identity_id, a.kind, a.handle, a.is_operator,
         b.id, t.batch_index, t.owner, t.record_type, t.change_kind
ORDER BY t.batch_index
`

type AuthorizeRRsetBatchParams struct {
	CredentialDigest []byte `db:"credential_digest"`
	IsSession        bool   `db:"is_session"`
	Tuples           []byte `db:"tuples"`
	Upstream         string `db:"upstream"`
	PowerDNSZoneID   string `db:"powerdns_zone_id"`
}

type AuthorizeRRsetBatchRow struct {
	TokenID              string   `db:"token_id"`
	IdentityID           string   `db:"identity_id"`
	IdentityKind         string   `db:"identity_kind"`
	IdentityHandle       string   `db:"identity_handle"`
	IsOperator           bool     `db:"is_operator"`
	ZoneBindingID        string   `db:"zone_binding_id"`
	BatchIndex           int32    `db:"batch_index"`
	Owner                string   `db:"owner"`
	RecordType           string   `db:"record_type"`
	ChangeKind           string   `db:"change_kind"`
	Allowed              bool     `db:"allowed"`
	MatchedDelegationIDs []string `db:"matched_delegation_ids"`
}

func (q *Queries) AuthorizeRRsetBatch(ctx context.Context, arg AuthorizeRRsetBatchParams) ([]AuthorizeRRsetBatchRow, error) {
	rows, err := q.db.Query(ctx, authorizeRRsetBatch,
		arg.CredentialDigest,
		arg.IsSession,
		arg.Tuples,
		arg.Upstream,
		arg.PowerDNSZoneID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthorizeRRsetBatchRow{}
	for rows.Next() {
		var i AuthorizeRRsetBatchRow
		if err := rows.Scan(
			&i.TokenID,
			&i.IdentityID,
			&i.IdentityKind,
			&i.IdentityHandle,
			&i.IsOperator,
			&i.ZoneBindingID,
			&i.BatchIndex,
			&i.Owner,
			&i.RecordType,
			&i.ChangeKind,
			&i.Allowed,
			&i.MatchedDelegationIDs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeOverdueDNSIntents = `-- name: CloseOverdueDNSIntents :many
WITH candidates AS (
    SELECT intent.id
    FROM audit_events AS intent
    WHERE intent.event_kind = 'dns_intent'
      AND intent.deadline_at <= statement_timestamp()
      AND cardinality($1::uuid[]) = $2
      AND NOT EXISTS (
          SELECT 1
          FROM audit_events AS outcome
          WHERE outcome.operation_id = intent.operation_id
            AND outcome.event_kind = 'dns_outcome'
      )
    ORDER BY intent.deadline_at, intent.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
),
numbered AS (
    SELECT intent.id, intent.occurred_at, intent.event_kind, intent.operation_id, intent.intent_event_id, intent.intent_event_kind, intent.request_id, intent.actor_identity_id, intent.actor_token_id, intent.action, intent.target_kind, intent.target_id, intent.result, intent.rrset_summary, intent.matched_delegation_ids, intent.details, intent.response_class, intent.response_code, intent.request_digest, intent.response_digest, intent.deadline_at, row_number() OVER (ORDER BY intent.deadline_at, intent.id) AS position
    FROM audit_events AS intent
    JOIN candidates ON candidates.id = intent.id
),
event_ids AS (
    SELECT value AS id, ordinality AS position
    FROM unnest($1::uuid[]) WITH ORDINALITY AS generated(value, ordinality)
)
INSERT INTO audit_events (
    id, event_kind, operation_id, intent_event_id, intent_event_kind,
    request_id, actor_identity_id, actor_token_id, action, target_kind,
    target_id, result, rrset_summary, matched_delegation_ids, details,
    response_class, request_digest
)
SELECT event_ids.id, 'dns_outcome', intent.operation_id, intent.id, 'dns_intent',
       intent.request_id, intent.actor_identity_id, intent.actor_token_id,
       intent.action, intent.target_kind, intent.target_id, 'unknown',
       intent.rrset_summary, intent.matched_delegation_ids,
       '{"closed_by":"deadline"}'::jsonb, 'deadline_elapsed', intent.request_digest
FROM numbered AS intent
JOIN event_ids ON event_ids.position = intent.position
ON CONFLICT (operation_id) WHERE event_kind = 'dns_outcome' DO NOTHING
RETURNING id
`

type CloseOverdueDNSIntentsParams struct {
	EventIDs []string `db:"event_ids"`
	RowLimit int32    `db:"row_limit"`
}

func (q *Queries) CloseOverdueDNSIntents(ctx context.Context, arg CloseOverdueDNSIntentsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, closeOverdueDNSIntents, arg.EventIDs, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEnabledOperators = `-- name: CountEnabledOperators :one
SELECT count(*)
FROM identities
WHERE enabled = true AND is_operator = true
`

func (q *Queries) CountEnabledOperators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnabledOperators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, identity_id, label, digest, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, identity_id, label, expires_at, revoked_at, created_at,
          CASE
              WHEN revoked_at IS NOT NULL THEN 'revoked'
              WHEN expires_at IS NOT NULL AND expires_at <= statement_timestamp() THEN 'expired'
              ELSE 'active'
          END::text AS status
`

type CreateAPITokenParams struct {
	ID         string             `db:"id"`
	IdentityID string             `db:"identity_id"`
	Label      string             `db:"label"`
	Digest     []byte             `db:"digest"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
}

type CreateAPITokenRow struct {
	ID         string             `db:"id"`
	IdentityID string             `db:"identity_id"`
	Label      string             `db:"label"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	Status     string             `db:"status"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (CreateAPITokenRow, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.IdentityID,
		arg.Label,
		arg.Digest,
		arg.ExpiresAt,
	)
	var i CreateAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Label,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const createDelegation = `-- name: CreateDelegation :one
INSERT INTO delegations (
    id, zone_binding_id, grantee_identity_id, grantee_group_id, created_by_identity_id
)
VALUES (
    $1, $2,
    NULLIF($3::text, '')::uuid,
    NULLIF($4::text, '')::uuid,
    $5
)
RETURNING id, zone_binding_id, grantee_identity_id, grantee_group_id,
          created_by_identity_id, revoked_by_identity_id, created_at, revoked_at
`

type CreateDelegationParams struct {
	ID                  string `db:"id"`
	ZoneBindingID       string `db:"zone_binding_id"`
	GranteeIdentityID   string `db:"grantee_identity_id"`
	GranteeGroupID      string `db:"grantee_group_id"`
	CreatedByIdentityID string `db:"created_by_identity_id"`
}

func (q *Queries) CreateDelegation(ctx context.Context, arg CreateDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, createDelegation,
		arg.ID,
		arg.ZoneBindingID,
		arg.GranteeIdentityID,
		arg.GranteeGroupID,
		arg.CreatedByIdentityID,
	)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.ZoneBindingID,
		&i.GranteeIdentityID,
		&i.GranteeGroupID,
		&i.CreatedByIdentityID,
		&i.RevokedByIdentityID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createDelegationChangeKind = `-- name: CreateDelegationChangeKind :exec
INSERT INTO delegation_change_kinds (delegation_id, change_kind)
VALUES ($1, $2)
`

type CreateDelegationChangeKindParams struct {
	DelegationID string `db:"delegation_id"`
	ChangeKind   string `db:"change_kind"`
}

func (q *Queries) CreateDelegationChangeKind(ctx context.Context, arg CreateDelegationChangeKindParams) error {
	_, err := q.db.Exec(ctx, createDelegationChangeKind, arg.DelegationID, arg.ChangeKind)
	return err
}

const createDelegationRecordType = `-- name: CreateDelegationRecordType :exec
INSERT INTO delegation_record_types (delegation_id, record_type)
VALUES ($1, $2)
`

type CreateDelegationRecordTypeParams struct {
	DelegationID string `db:"delegation_id"`
	RecordType   string `db:"record_type"`
}

func (q *Queries) CreateDelegationRecordType(ctx context.Context, arg CreateDelegationRecordTypeParams) error {
	_, err := q.db.Exec(ctx, createDelegationRecordType, arg.DelegationID, arg.RecordType)
	return err
}

const createDelegationSelector = `-- name: CreateDelegationSelector :exec
INSERT INTO delegation_selectors (
    delegation_id, position, kind, selector, sql_like_pattern
)
VALUES ($1, $2, $3, $4, $5)
`

type CreateDelegationSelectorParams struct {
	DelegationID   string `db:"delegation_id"`
	Position       int16  `db:"position"`
	Kind           string `db:"kind"`
	Selector       string `db:"selector"`
	SQLLikePattern string `db:"sql_like_pattern"`
}

func (q *Queries) CreateDelegationSelector(ctx context.Context, arg CreateDelegationSelectorParams) error {
	_, err := q.db.Exec(ctx, createDelegationSelector,
		arg.DelegationID,
		arg.Position,
		arg.Kind,
		arg.Selector,
		arg.SQLLikePattern,
	)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, handle, display_name)
VALUES ($1, $2, $3)
RETURNING id, handle, display_name, enabled, created_at, updated_at
`

type CreateGroupParams struct {
	ID          string  `db:"id"`
	Handle      string  `db:"handle"`
	DisplayName *string `db:"display_name"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.ID, arg.Handle, arg.DisplayName)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (id, kind, handle, display_name)
VALUES ($1, $2, $3, $4)
RETURNING id, kind, handle, display_name, enabled, is_operator, created_at, updated_at
`

type CreateIdentityParams struct {
	ID          string  `db:"id"`
	Kind        string  `db:"kind"`
	Handle      string  `db:"handle"`
	DisplayName *string `db:"display_name"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.ID,
		arg.Kind,
		arg.Handle,
		arg.DisplayName,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.IsOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstallationMetadata = `-- name: CreateInstallationMetadata :one
INSERT INTO installation_metadata (installation_id)
VALUES ($1)
RETURNING singleton, installation_id, initialized_at, restore_required, restore_finalized_at
`

func (q *Queries) CreateInstallationMetadata(ctx context.Context, installationID string) (InstallationMetadata, error) {
	row := q.db.QueryRow(ctx, createInstallationMetadata, installationID)
	var i InstallationMetadata
	err := row.Scan(
		&i.Singleton,
		&i.InstallationID,
		&i.InitializedAt,
		&i.RestoreRequired,
		&i.RestoreFinalizedAt,
	)
	return i, err
}

const createOperatorIdentity = `-- name: CreateOperatorIdentity :one
INSERT INTO identities (id, kind, handle, display_name, is_operator)
VALUES ($1, 'user', $2, $3, true)
RETURNING id, kind, handle, display_name, enabled, is_operator, created_at, updated_at
`

type CreateOperatorIdentityParams struct {
	ID          string  `db:"id"`
	Handle      string  `db:"handle"`
	DisplayName *string `db:"display_name"`
}

func (q *Queries) CreateOperatorIdentity(ctx context.Context, arg CreateOperatorIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createOperatorIdentity, arg.ID, arg.Handle, arg.DisplayName)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.IsOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createZoneBinding = `-- name: CreateZoneBinding :one
INSERT INTO zone_bindings (
    id, generation, upstream, powerdns_zone_id, zone_name, created_by_identity_id
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, generation, upstream, powerdns_zone_id, zone_name,
          created_by_identity_id, retired_by_identity_id, created_at, retired_at
`

type CreateZoneBindingParams struct {
	ID                  string `db:"id"`
	Generation          int64  `db:"generation"`
	Upstream            string `db:"upstream"`
	PowerDNSZoneID      string `db:"powerdns_zone_id"`
	ZoneName            string `db:"zone_name"`
	CreatedByIdentityID string `db:"created_by_identity_id"`
}

func (q *Queries) CreateZoneBinding(ctx context.Context, arg CreateZoneBindingParams) (ZoneBinding, error) {
	row := q.db.QueryRow(ctx, createZoneBinding,
		arg.ID,
		arg.Generation,
		arg.Upstream,
		arg.PowerDNSZoneID,
		arg.ZoneName,
		arg.CreatedByIdentityID,
	)
	var i ZoneBinding
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.Upstream,
		&i.PowerDNSZoneID,
		&i.ZoneName,
		&i.CreatedByIdentityID,
		&i.RetiredByIdentityID,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const finalizeInstallationRestore = `-- name: FinalizeInstallationRestore :one
UPDATE installation_metadata
SET restore_required = false,
    restore_finalized_at = statement_timestamp()
WHERE singleton = true
RETURNING singleton, installation_id, initialized_at, restore_required, restore_finalized_at
`

func (q *Queries) FinalizeInstallationRestore(ctx context.Context) (InstallationMetadata, error) {
	row := q.db.QueryRow(ctx, finalizeInstallationRestore)
	var i InstallationMetadata
	err := row.Scan(
		&i.Singleton,
		&i.InstallationID,
		&i.InitializedAt,
		&i.RestoreRequired,
		&i.RestoreFinalizedAt,
	)
	return i, err
}

const getAPITokenMetadata = `-- name: GetAPITokenMetadata :one
SELECT id, identity_id, label, expires_at, revoked_at, created_at,
       CASE
           WHEN revoked_at IS NOT NULL THEN 'revoked'
           WHEN expires_at IS NOT NULL AND expires_at <= statement_timestamp() THEN 'expired'
           ELSE 'active'
       END::text AS status
FROM api_tokens
WHERE identity_id = $1 AND id = $2
`

type GetAPITokenMetadataParams struct {
	IdentityID string `db:"identity_id"`
	ID         string `db:"id"`
}

type GetAPITokenMetadataRow struct {
	ID         string             `db:"id"`
	IdentityID string             `db:"identity_id"`
	Label      string             `db:"label"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	Status     string             `db:"status"`
}

func (q *Queries) GetAPITokenMetadata(ctx context.Context, arg GetAPITokenMetadataParams) (GetAPITokenMetadataRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenMetadata, arg.IdentityID, arg.ID)
	var i GetAPITokenMetadataRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Label,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getActiveZoneBindingByUpstreamZoneIDForUpdate = `-- name: GetActiveZoneBindingByUpstreamZoneIDForUpdate :one
SELECT id, generation, upstream, powerdns_zone_id, zone_name,
       created_by_identity_id, retired_by_identity_id, created_at, retired_at
FROM zone_bindings
WHERE upstream = $1
  AND powerdns_zone_id = $2
  AND retired_at IS NULL
FOR UPDATE
`

type GetActiveZoneBindingByUpstreamZoneIDForUpdateParams struct {
	Upstream       string `db:"upstream"`
	PowerDNSZoneID string `db:"powerdns_zone_id"`
}

func (q *Queries) GetActiveZoneBindingByUpstreamZoneIDForUpdate(ctx context.Context, arg GetActiveZoneBindingByUpstreamZoneIDForUpdateParams) (ZoneBinding, error) {
	row := q.db.QueryRow(ctx, getActiveZoneBindingByUpstreamZoneIDForUpdate, arg.Upstream, arg.PowerDNSZoneID)
	var i ZoneBinding
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.Upstream,
		&i.PowerDNSZoneID,
		&i.ZoneName,
		&i.CreatedByIdentityID,
		&i.RetiredByIdentityID,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getAuditEventByID = `-- name: GetAuditEventByID :one
SELECT id, occurred_at, event_kind, operation_id, intent_event_id,
       request_id, actor_identity_id, actor_token_id, action, target_kind,
       target_id, result, rrset_summary, matched_delegation_ids, details,
       response_class, response_code, request_digest, response_digest, deadline_at
FROM audit_events
WHERE id = $1
`

type GetAuditEventByIDRow struct {
	ID                   string             `db:"id"`
	OccurredAt           pgtype.Timestamptz `db:"occurred_at"`
	EventKind            string             `db:"event_kind"`
	OperationID          *string            `db:"operation_id"`
	IntentEventID        *string            `db:"intent_event_id"`
	RequestID            string             `db:"request_id"`
	ActorIdentityID      *string            `db:"actor_identity_id"`
	ActorTokenID         *string            `db:"actor_token_id"`
	Action               string             `db:"action"`
	TargetKind           string             `db:"target_kind"`
	TargetID             string             `db:"target_id"`
	Result               string             `db:"result"`
	RRsetSummary         []byte             `db:"rrset_summary"`
	MatchedDelegationIDs []string           `db:"matched_delegation_ids"`
	Details              []byte             `db:"details"`
	ResponseClass        *string            `db:"response_class"`
	ResponseCode         *int32             `db:"response_code"`
	RequestDigest        []byte             `db:"request_digest"`
	ResponseDigest       []byte             `db:"response_digest"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at"`
}

func (q *Queries) GetAuditEventByID(ctx context.Context, id string) (GetAuditEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getAuditEventByID, id)
	var i GetAuditEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.EventKind,
		&i.OperationID,
		&i.IntentEventID,
		&i.RequestID,
		&i.ActorIdentityID,
		&i.ActorTokenID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Result,
		&i.RRsetSummary,
		&i.MatchedDelegationIDs,
		&i.Details,
		&i.ResponseClass,
		&i.ResponseCode,
		&i.RequestDigest,
		&i.ResponseDigest,
		&i.DeadlineAt,
	)
	return i, err
}

const getBootstrapState = `-- name: GetBootstrapState :one
SELECT
    (SELECT count(*) FROM installation_metadata) AS installations,
    (SELECT count(*) FROM identities) AS identities
`

type GetBootstrapStateRow struct {
	Installations int64 `db:"installations"`
	Identities    int64 `db:"identities"`
}

func (q *Queries) GetBootstrapState(ctx context.Context) (GetBootstrapStateRow, error) {
	row := q.db.QueryRow(ctx, getBootstrapState)
	var i GetBootstrapStateRow
	err := row.Scan(&i.Installations, &i.Identities)
	return i, err
}

const getDNSOutcomeByOperationID = `-- name: GetDNSOutcomeByOperationID :one
SELECT id, event_kind, operation_id::text AS operation_id,
       intent_event_id::text AS intent_event_id, result,
       response_class, response_code, response_digest, occurred_at
FROM audit_events
WHERE operation_id = NULLIF($1::text, '')::uuid
  AND event_kind = 'dns_outcome'
`

type GetDNSOutcomeByOperationIDRow struct {
	ID             string             `db:"id"`
	EventKind      string             `db:"event_kind"`
	OperationID    string             `db:"operation_id"`
	IntentEventID  string             `db:"intent_event_id"`
	Result         string             `db:"result"`
	ResponseClass  *string            `db:"response_class"`
	ResponseCode   *int32             `db:"response_code"`
	ResponseDigest []byte             `db:"response_digest"`
	OccurredAt     pgtype.Timestamptz `db:"occurred_at"`
}

func (q *Queries) GetDNSOutcomeByOperationID(ctx context.Context, operationID string) (GetDNSOutcomeByOperationIDRow, error) {
	row := q.db.QueryRow(ctx, getDNSOutcomeByOperationID, operationID)
	var i GetDNSOutcomeByOperationIDRow
	err := row.Scan(
		&i.ID,
		&i.EventKind,
		&i.OperationID,
		&i.IntentEventID,
		&i.Result,
		&i.ResponseClass,
		&i.ResponseCode,
		&i.ResponseDigest,
		&i.OccurredAt,
	)
	return i, err
}

const getDelegationByID = `-- name: GetDelegationByID :one
SELECT id, zone_binding_id, grantee_identity_id, grantee_group_id,
       created_by_identity_id, revoked_by_identity_id, created_at, revoked_at
FROM delegations
WHERE id = $1
`

func (q *Queries) GetDelegationByID(ctx context.Context, id string) (Delegation, error) {
	row := q.db.QueryRow(ctx, getDelegationByID, id)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.ZoneBindingID,
		&i.GranteeIdentityID,
		&i.GranteeGroupID,
		&i.CreatedByIdentityID,
		&i.RevokedByIdentityID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDelegationDetails = `-- name: GetDelegationDetails :one
SELECT id, zone_binding_id,
       CASE WHEN grantee_identity_id IS NOT NULL THEN 'identity' ELSE 'group' END::text AS grantee_kind,
       COALESCE(grantee_identity_id, grantee_group_id)::text AS grantee_id,
       created_at, revoked_at
FROM delegations
WHERE id = $1
`

type GetDelegationDetailsRow struct {
	ID            string             `db:"id"`
	ZoneBindingID string             `db:"zone_binding_id"`
	GranteeKind   string             `db:"grantee_kind"`
	GranteeID     string             `db:"grantee_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	RevokedAt     pgtype.Timestamptz `db:"revoked_at"`
}

func (q *Queries) GetDelegationDetails(ctx context.Context, id string) (GetDelegationDetailsRow, error) {
	row := q.db.QueryRow(ctx, getDelegationDetails, id)
	var i GetDelegationDetailsRow
	err := row.Scan(
		&i.ID,
		&i.ZoneBindingID,
		&i.GranteeKind,
		&i.GranteeID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDelegationForUpdate = `-- name: GetDelegationForUpdate :one
SELECT id, zone_binding_id, grantee_identity_id, grantee_group_id,
       created_by_identity_id, revoked_by_identity_id, created_at, revoked_at
FROM delegations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetDelegationForUpdate(ctx context.Context, id string) (Delegation, error) {
	row := q.db.QueryRow(ctx, getDelegationForUpdate, id)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.ZoneBindingID,
		&i.GranteeIdentityID,
		&i.GranteeGroupID,
		&i.CreatedByIdentityID,
		&i.RevokedByIdentityID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, handle, display_name, enabled, created_at, updated_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupForUpdate = `-- name: GetGroupForUpdate :one
SELECT id, handle, display_name, enabled, created_at, updated_at
FROM groups
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetGroupForUpdate(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupForUpdate, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMembership = `-- name: GetGroupMembership :one
SELECT group_id, identity_id, added_by_identity_id, created_at
FROM group_memberships
WHERE group_id = $1 AND identity_id = $2
`

type GetGroupMembershipParams struct {
	GroupID    string `db:"group_id"`
	IdentityID string `db:"identity_id"`
}

func (q *Queries) GetGroupMembership(ctx context.Context, arg GetGroupMembershipParams) (GroupMembership, error) {
	row := q.db.QueryRow(ctx, getGroupMembership, arg.GroupID, arg.IdentityID)
	var i GroupMembership
	err := row.Scan(
		&i.GroupID,
		&i.IdentityID,
		&i.AddedByIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityByHandleForUpdate = `-- name: GetIdentityByHandleForUpdate :one
SELECT id, kind, handle, display_name, enabled, is_operator, created_at, updated_at
FROM identities
WHERE handle = $1
FOR UPDATE
`

func (q *Queries) GetIdentityByHandleForUpdate(ctx context.Context, handle string) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByHandleForUpdate, handle)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.IsOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByID = `-- name: GetIdentityByID :one
SELECT id, kind, handle, display_name, enabled, is_operator, created_at, updated_at
FROM identities
WHERE id = $1
`

func (q *Queries) GetIdentityByID(ctx context.Context, id string) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByID, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.IsOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityForUpdate = `-- name: GetIdentityForUpdate :one
SELECT id, kind, handle, display_name, enabled, is_operator, created_at, updated_at
FROM identities
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetIdentityForUpdate(ctx context.Context, id string) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityForUpdate, id)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.IsOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationMetadata = `-- name: GetInstallationMetadata :one
SELECT installation_id, initialized_at, restore_required, restore_finalized_at
FROM installation_metadata
WHERE singleton = true
`

type GetInstallationMetadataRow struct {
	InstallationID     string             `db:"installation_id"`
	InitializedAt      pgtype.Timestamptz `db:"initialized_at"`
	RestoreRequired    bool               `db:"restore_required"`
	RestoreFinalizedAt pgtype.Timestamptz `db:"restore_finalized_at"`
}

func (q *Queries) GetInstallationMetadata(ctx context.Context) (GetInstallationMetadataRow, error) {
	row := q.db.QueryRow(ctx, getInstallationMetadata)
	var i GetInstallationMetadataRow
	err := row.Scan(
		&i.InstallationID,
		&i.InitializedAt,
		&i.RestoreRequired,
		&i.RestoreFinalizedAt,
	)
	return i, err
}

const getZoneBindingByID = `-- name: GetZoneBindingByID :one
SELECT id, generation, upstream, powerdns_zone_id, zone_name,
       created_by_identity_id, retired_by_identity_id, created_at, retired_at
FROM zone_bindings
WHERE id = $1
`

func (q *Queries) GetZoneBindingByID(ctx context.Context, id string) (ZoneBinding, error) {
	row := q.db.QueryRow(ctx, getZoneBindingByID, id)
	var i ZoneBinding
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.Upstream,
		&i.PowerDNSZoneID,
		&i.ZoneName,
		&i.CreatedByIdentityID,
		&i.RetiredByIdentityID,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getZoneBindingForUpdate = `-- name: GetZoneBindingForUpdate :one
SELECT id, generation, upstream, powerdns_zone_id, zone_name,
       created_by_identity_id, retired_by_identity_id, created_at, retired_at
FROM zone_bindings
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetZoneBindingForUpdate(ctx context.Context, id string) (ZoneBinding, error) {
	row := q.db.QueryRow(ctx, getZoneBindingForUpdate, id)
	var i ZoneBinding
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.Upstream,
		&i.PowerDNSZoneID,
		&i.ZoneName,
		&i.CreatedByIdentityID,
		&i.RetiredByIdentityID,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const getZoneDeletionReconciliationState = `-- name: GetZoneDeletionReconciliationState :one
SELECT
    EXISTS (
        SELECT 1
        FROM audit_events AS intent
        WHERE intent.event_kind = 'dns_intent'
          AND intent.action = 'powerdns.zone.delete'
          AND intent.target_kind = 'zone_binding'
          AND intent.target_id = $1
    ) AS has_attempt,
    EXISTS (
        SELECT 1
        FROM audit_events AS intent
        LEFT JOIN audit_events AS outcome
          ON outcome.intent_event_id = intent.id
         AND outcome.event_kind = 'dns_outcome'
        WHERE intent.event_kind = 'dns_intent'
          AND intent.action = 'powerdns.zone.delete'
          AND intent.target_kind = 'zone_binding'
          AND intent.target_id = $1
          AND outcome.id IS NULL
    ) AS has_pending,
    EXISTS (
        SELECT 1
        FROM audit_events AS intent
        JOIN audit_events AS outcome
          ON outcome.intent_event_id = intent.id
         AND outcome.event_kind = 'dns_outcome'
        WHERE intent.event_kind = 'dns_intent'
          AND intent.action = 'powerdns.zone.delete'
          AND intent.target_kind = 'zone_binding'
          AND intent.target_id = $1
          AND outcome.result = 'succeeded'
    ) AS has_succeeded,
    EXISTS (
        SELECT 1
        FROM audit_events AS intent
        JOIN audit_events AS outcome
          ON outcome.intent_event_id = intent.id
         AND outcome.event_kind = 'dns_outcome'
        WHERE intent.event_kind = 'dns_intent'
          AND intent.action = 'powerdns.zone.delete'
          AND intent.target_kind = 'zone_binding'
          AND intent.target_id = $1
          AND outcome.result IN ('failed', 'unknown')
    ) AS has_retryable,
    EXISTS (
        SELECT 1
        FROM audit_events AS event
        WHERE event.event_kind = 'management'
          AND event.action = 'zone_binding.confirm_absent'
          AND event.target_kind = 'zone_binding'
          AND event.target_id = $1
          AND event.result = 'succeeded'
    ) AS confirmed_absent
`

type GetZoneDeletionReconciliationStateRow struct {
	HasAttempt      bool `db:"has_attempt"`
	HasPending      bool `db:"has_pending"`
	HasSucceeded    bool `db:"has_succeeded"`
	HasRetryable    bool `db:"has_retryable"`
	ConfirmedAbsent bool `db:"confirmed_absent"`
}

func (q *Queries) GetZoneDeletionReconciliationState(ctx context.Context, bindingID string) (GetZoneDeletionReconciliationStateRow, error) {
	row := q.db.QueryRow(ctx, getZoneDeletionReconciliationState, bindingID)
	var i GetZoneDeletionReconciliationStateRow
	err := row.Scan(
		&i.HasAttempt,
		&i.HasPending,
		&i.HasSucceeded,
		&i.HasRetryable,
		&i.ConfirmedAbsent,
	)
	return i, err
}

const insertAuthorizationDeniedAudit = `-- name: InsertAuthorizationDeniedAudit :one
INSERT INTO audit_events (
    id, event_kind, request_id, actor_identity_id, actor_token_id,
    action, target_kind, target_id, result, details, request_digest
)
VALUES (
    $1, 'authorization_denied', $2,
    NULLIF($3::text, '')::uuid,
    NULLIF($4::text, '')::uuid,
    $5, $6, $7,
    'denied', $8, $9
)
RETURNING id, occurred_at, event_kind, operation_id, intent_event_id,
          request_id, actor_identity_id, actor_token_id, action, target_kind,
          target_id, result, rrset_summary, matched_delegation_ids, details,
          response_class, response_code, request_digest, response_digest, deadline_at
`

type InsertAuthorizationDeniedAuditParams struct {
	ID              string `db:"id"`
	RequestID       string `db:"request_id"`
	ActorIdentityID string `db:"actor_identity_id"`
	ActorTokenID    string `db:"actor_token_id"`
	Action          string `db:"action"`
	TargetKind      string `db:"target_kind"`
	TargetID        string `db:"target_id"`
	Details         []byte `db:"details"`
	RequestDigest   []byte `db:"request_digest"`
}

type InsertAuthorizationDeniedAuditRow struct {
	ID                   string             `db:"id"`
	OccurredAt           pgtype.Timestamptz `db:"occurred_at"`
	EventKind            string             `db:"event_kind"`
	OperationID          *string            `db:"operation_id"`
	IntentEventID        *string            `db:"intent_event_id"`
	RequestID            string             `db:"request_id"`
	ActorIdentityID      *string            `db:"actor_identity_id"`
	ActorTokenID         *string            `db:"actor_token_id"`
	Action               string             `db:"action"`
	TargetKind           string             `db:"target_kind"`
	TargetID             string             `db:"target_id"`
	Result               string             `db:"result"`
	RRsetSummary         []byte             `db:"rrset_summary"`
	MatchedDelegationIDs []string           `db:"matched_delegation_ids"`
	Details              []byte             `db:"details"`
	ResponseClass        *string            `db:"response_class"`
	ResponseCode         *int32             `db:"response_code"`
	RequestDigest        []byte             `db:"request_digest"`
	ResponseDigest       []byte             `db:"response_digest"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at"`
}

func (q *Queries) InsertAuthorizationDeniedAudit(ctx context.Context, arg InsertAuthorizationDeniedAuditParams) (InsertAuthorizationDeniedAuditRow, error) {
	row := q.db.QueryRow(ctx, insertAuthorizationDeniedAudit,
		arg.ID,
		arg.RequestID,
		arg.ActorIdentityID,
		arg.ActorTokenID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Details,
		arg.RequestDigest,
	)
	var i InsertAuthorizationDeniedAuditRow
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.EventKind,
		&i.OperationID,
		&i.IntentEventID,
		&i.RequestID,
		&i.ActorIdentityID,
		&i.ActorTokenID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Result,
		&i.RRsetSummary,
		&i.MatchedDelegationIDs,
		&i.Details,
		&i.ResponseClass,
		&i.ResponseCode,
		&i.RequestDigest,
		&i.ResponseDigest,
		&i.DeadlineAt,
	)
	return i, err
}

const insertDNSIntent = `-- name: InsertDNSIntent :one
INSERT INTO audit_events (
    id, event_kind, operation_id, request_id, actor_identity_id, actor_token_id,
    action, target_kind, target_id, result, rrset_summary,
    matched_delegation_ids, details, request_digest, deadline_at
)
VALUES (
    $1, 'dns_intent', NULLIF($2::text, '')::uuid,
    $3,
    NULLIF($4::text, '')::uuid,
    NULLIF($5::text, '')::uuid,
    $6, $7, $8,
    'pending', $9,
    COALESCE($10::uuid[], '{}'::uuid[]),
    '{}'::jsonb, $11, $12
)
RETURNING id, occurred_at, event_kind, operation_id, intent_event_id,
          request_id, actor_identity_id, actor_token_id, action, target_kind,
          target_id, result, rrset_summary, matched_delegation_ids, details,
          response_class, response_code, request_digest, response_digest, deadline_at
`

type InsertDNSIntentParams struct {
	ID                   string             `db:"id"`
	OperationID          string             `db:"operation_id"`
	RequestID            string             `db:"request_id"`
	ActorIdentityID      string             `db:"actor_identity_id"`
	ActorTokenID         string             `db:"actor_token_id"`
	Action               string             `db:"action"`
	TargetKind           string             `db:"target_kind"`
	TargetID             string             `db:"target_id"`
	RRsetSummary         []byte             `db:"rrset_summary"`
	MatchedDelegationIDs []string           `db:"matched_delegation_ids"`
	RequestDigest        []byte             `db:"request_digest"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at"`
}

type InsertDNSIntentRow struct {
	ID                   string             `db:"id"`
	OccurredAt           pgtype.Timestamptz `db:"occurred_at"`
	EventKind            string             `db:"event_kind"`
	OperationID          *string            `db:"operation_id"`
	IntentEventID        *string            `db:"intent_event_id"`
	RequestID            string             `db:"request_id"`
	ActorIdentityID      *string            `db:"actor_identity_id"`
	ActorTokenID         *string            `db:"actor_token_id"`
	Action               string             `db:"action"`
	TargetKind           string             `db:"target_kind"`
	TargetID             string             `db:"target_id"`
	Result               string             `db:"result"`
	RRsetSummary         []byte             `db:"rrset_summary"`
	MatchedDelegationIDs []string           `db:"matched_delegation_ids"`
	Details              []byte             `db:"details"`
	ResponseClass        *string            `db:"response_class"`
	ResponseCode         *int32             `db:"response_code"`
	RequestDigest        []byte             `db:"request_digest"`
	ResponseDigest       []byte             `db:"response_digest"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at"`
}

func (q *Queries) InsertDNSIntent(ctx context.Context, arg InsertDNSIntentParams) (InsertDNSIntentRow, error) {
	row := q.db.QueryRow(ctx, insertDNSIntent,
		arg.ID,
		arg.OperationID,
		arg.RequestID,
		arg.ActorIdentityID,
		arg.ActorTokenID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.RRsetSummary,
		arg.MatchedDelegationIDs,
		arg.RequestDigest,
		arg.DeadlineAt,
	)
	var i InsertDNSIntentRow
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.EventKind,
		&i.OperationID,
		&i.IntentEventID,
		&i.RequestID,
		&i.ActorIdentityID,
		&i.ActorTokenID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Result,
		&i.RRsetSummary,
		&i.MatchedDelegationIDs,
		&i.Details,
		&i.ResponseClass,
		&i.ResponseCode,
		&i.RequestDigest,
		&i.ResponseDigest,
		&i.DeadlineAt,
	)
	return i, err
}

const insertDNSOutcome = `-- name: InsertDNSOutcome :execrows
INSERT INTO audit_events (
    id, event_kind, operation_id, intent_event_id, intent_event_kind,
    request_id, actor_identity_id, actor_token_id, action, target_kind,
    target_id, result, rrset_summary, matched_delegation_ids, details,
    response_class, response_code, request_digest, response_digest
)
SELECT $1, 'dns_outcome', intent.operation_id, intent.id, 'dns_intent',
       intent.request_id, intent.actor_identity_id, intent.actor_token_id,
       intent.action, intent.target_kind, intent.target_id, $2,
       intent.rrset_summary, intent.matched_delegation_ids, '{}'::jsonb,
       NULLIF($3::text, ''), $4::integer,
       intent.request_digest, NULLIF($5::bytea, ''::bytea)
FROM audit_events AS intent
WHERE intent.id = NULLIF($6::text, '')::uuid
  AND intent.operation_id = NULLIF($7::text, '')::uuid
  AND intent.event_kind = 'dns_intent'
ON CONFLICT (operation_id) WHERE event_kind = 'dns_outcome' DO NOTHING
`

type InsertDNSOutcomeParams struct {
	ID             string `db:"id"`
	Result         string `db:"result"`
	ResponseClass  string `db:"response_class"`
	ResponseCode   *int32 `db:"response_code"`
	ResponseDigest []byte `db:"response_digest"`
	IntentEventID  string `db:"intent_event_id"`
	OperationID    string `db:"operation_id"`
}

func (q *Queries) InsertDNSOutcome(ctx context.Context, arg InsertDNSOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertDNSOutcome,
		arg.ID,
		arg.Result,
		arg.ResponseClass,
		arg.ResponseCode,
		arg.ResponseDigest,
		arg.IntentEventID,
		arg.OperationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertManagementAudit = `-- name: InsertManagementAudit :one
INSERT INTO audit_events (
    id, event_kind, request_id, actor_identity_id, actor_token_id,
    action, target_kind, target_id, result, details
)
VALUES (
    $1, 'management', $2,
    NULLIF($3::text, '')::uuid,
    NULLIF($4::text, '')::uuid,
    $5, $6, $7,
    $8, $9
)
RETURNING id, occurred_at, event_kind, operation_id, intent_event_id,
          request_id, actor_identity_id, actor_token_id, action, target_kind,
          target_id, result, rrset_summary, matched_delegation_ids, details,
          response_class, response_code, request_digest, response_digest, deadline_at
`

type InsertManagementAuditParams struct {
	ID              string `db:"id"`
	RequestID       string `db:"request_id"`
	ActorIdentityID string `db:"actor_identity_id"`
	ActorTokenID    string `db:"actor_token_id"`
	Action          string `db:"action"`
	TargetKind      string `db:"target_kind"`
	TargetID        string `db:"target_id"`
	Result          string `db:"result"`
	Details         []byte `db:"details"`
}

type InsertManagementAuditRow struct {
	ID                   string             `db:"id"`
	OccurredAt           pgtype.Timestamptz `db:"occurred_at"`
	EventKind            string             `db:"event_kind"`
	OperationID          *string            `db:"operation_id"`
	IntentEventID        *string            `db:"intent_event_id"`
	RequestID            string             `db:"request_id"`
	ActorIdentityID      *string            `db:"actor_identity_id"`
	ActorTokenID         *string            `db:"actor_token_id"`
	Action               string             `db:"action"`
	TargetKind           string             `db:"target_kind"`
	TargetID             string             `db:"target_id"`
	Result               string             `db:"result"`
	RRsetSummary         []byte             `db:"rrset_summary"`
	MatchedDelegationIDs []string           `db:"matched_delegation_ids"`
	Details              []byte             `db:"details"`
	ResponseClass        *string            `db:"response_class"`
	ResponseCode         *int32             `db:"response_code"`
	RequestDigest        []byte             `db:"request_digest"`
	ResponseDigest       []byte             `db:"response_digest"`
	DeadlineAt           pgtype.Timestamptz `db:"deadline_at"`
}

func (q *Queries) InsertManagementAudit(ctx context.Context, arg InsertManagementAuditParams) (InsertManagementAuditRow, error) {
	row := q.db.QueryRow(ctx, insertManagementAudit,
		arg.ID,
		arg.RequestID,
		arg.ActorIdentityID,
		arg.ActorTokenID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Result,
		arg.Details,
	)
	var i InsertManagementAuditRow
	err := row.Scan(
		&i.ID,
		&i.OccurredAt,
		&i.EventKind,
		&i.OperationID,
		&i.IntentEventID,
		&i.RequestID,
		&i.ActorIdentityID,
		&i.ActorTokenID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Result,
		&i.RRsetSummary,
		&i.MatchedDelegationIDs,
		&i.Details,
		&i.ResponseClass,
		&i.ResponseCode,
		&i.RequestDigest,
		&i.ResponseDigest,
		&i.DeadlineAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, identity_id, label, expires_at, revoked_at, created_at,
       CASE
           WHEN revoked_at IS NOT NULL THEN 'revoked'
           WHEN expires_at IS NOT NULL AND expires_at <= statement_timestamp() THEN 'expired'
           ELSE 'active'
       END::text AS status
FROM api_tokens
WHERE identity_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (created_at, id) < (
          $2,
          NULLIF($3::text, '')::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAPITokensParams struct {
	IdentityID     string             `db:"identity_id"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        string             `db:"after_id"`
	RowLimit       int32              `db:"row_limit"`
}

type ListAPITokensRow struct {
	ID         string             `db:"id"`
	IdentityID string             `db:"identity_id"`
	Label      string             `db:"label"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	Status     string             `db:"status"`
}

func (q *Queries) ListAPITokens(ctx context.Context, arg ListAPITokensParams) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens,
		arg.IdentityID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.IdentityID,
			&i.Label,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveZoneBindingCandidates = `-- name: ListActiveZoneBindingCandidates :many
SELECT id, generation, upstream, powerdns_zone_id, zone_name,
       created_by_identity_id, retired_by_identity_id, created_at, retired_at
FROM zone_bindings
WHERE upstream = $1
  AND retired_at IS NULL
  AND (powerdns_zone_id = $2 OR zone_name = $3)
ORDER BY id
`

type ListActiveZoneBindingCandidatesParams struct {
	Upstream       string `db:"upstream"`
	PowerDNSZoneID string `db:"powerdns_zone_id"`
	ZoneName       string `db:"zone_name"`
}

func (q *Queries) ListActiveZoneBindingCandidates(ctx context.Context, arg ListActiveZoneBindingCandidatesParams) ([]ZoneBinding, error) {
	rows, err := q.db.Query(ctx, listActiveZoneBindingCandidates, arg.Upstream, arg.PowerDNSZoneID, arg.ZoneName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZoneBinding{}
	for rows.Next() {
		var i ZoneBinding
		if err := rows.Scan(
			&i.ID,
			&i.Generation,
			&i.Upstream,
			&i.PowerDNSZoneID,
			&i.ZoneName,
			&i.CreatedByIdentityID,
			&i.RetiredByIdentityID,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditRecords = `-- name: ListAuditRecords :many
SELECT id, occurred_at, request_id,
       COALESCE(actor_identity_id::text, '')::text AS actor_id,
       action, target_kind, target_id, result, details
FROM audit_events
WHERE (NULLIF($1::text, '') IS NULL
       OR actor_identity_id = NULLIF($1::text, '')::uuid)
  AND (NULLIF($2::text, '') IS NULL OR action = $2)
  AND (NULLIF($3::text, '') IS NULL OR target_kind = $3)
  AND (NULLIF($4::text, '') IS NULL OR target_id = $4)
  AND (NULLIF($5::text, '') IS NULL OR result = $5)
  AND (
      $6::timestamptz IS NULL
      OR (occurred_at, id) < (
          $6,
          NULLIF($7::text, '')::uuid
      )
  )
ORDER BY occurred_at DESC, id DESC
LIMIT $8
`

type ListAuditRecordsParams struct {
	ActorID         string             `db:"actor_id"`
	Action          string             `db:"action"`
	TargetKind      string             `db:"target_kind"`
	TargetID        string             `db:"target_id"`
	Result          string             `db:"result"`
	AfterOccurredAt pgtype.Timestamptz `db:"after_occurred_at"`
	AfterID         string             `db:"after_id"`
	RowLimit        int32              `db:"row_limit"`
}

type ListAuditRecordsRow struct {
	ID         string             `db:"id"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at"`
	RequestID  string             `db:"request_id"`
	ActorID    string             `db:"actor_id"`
	Action     string             `db:"action"`
	TargetKind string             `db:"target_kind"`
	TargetID   string             `db:"target_id"`
	Result     string             `db:"result"`
	Details    []byte             `db:"details"`
}

func (q *Queries) ListAuditRecords(ctx context.Context, arg ListAuditRecordsParams) ([]ListAuditRecordsRow, error) {
	rows, err := q.db.Query(ctx, listAuditRecords,
		arg.ActorID,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Result,
		arg.AfterOccurredAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRecordsRow{}
	for rows.Next() {
		var i ListAuditRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.RequestID,
			&i.ActorID,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Result,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelegationChangeKindsByIDs = `-- name: ListDelegationChangeKindsByIDs :many
SELECT delegation_id, change_kind
FROM delegation_change_kinds
WHERE delegation_id = ANY($1::uuid[])
ORDER BY delegation_id, change_kind
`

func (q *Queries) ListDelegationChangeKindsByIDs(ctx context.Context, delegationIds []string) ([]DelegationChangeKind, error) {
	rows, err := q.db.Query(ctx, listDelegationChangeKindsByIDs, delegationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DelegationChangeKind{}
	for rows.Next() {
		var i DelegationChangeKind
		if err := rows.Scan(&i.DelegationID, &i.ChangeKind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelegationDetails = `-- name: ListDelegationDetails :many
SELECT id, zone_binding_id,
       CASE WHEN grantee_identity_id IS NOT NULL THEN 'identity' ELSE 'group' END::text AS grantee_kind,
       COALESCE(grantee_identity_id, grantee_group_id)::text AS grantee_id,
       created_at, revoked_at
FROM delegations
WHERE (NULLIF($1::text, '') IS NULL
       OR zone_binding_id = NULLIF($1::text, '')::uuid)
  AND (NULLIF($2::text, '') IS NULL
       OR grantee_identity_id = NULLIF($2::text, '')::uuid
       OR grantee_group_id = NULLIF($2::text, '')::uuid)
  AND ($3::boolean IS NULL
       OR (revoked_at IS NULL) = $3)
  AND (
      $4::timestamptz IS NULL
      OR (created_at, id) < (
          $4,
          NULLIF($5::text, '')::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListDelegationDetailsParams struct {
	ZoneBindingID  string             `db:"zone_binding_id"`
	GranteeID      string             `db:"grantee_id"`
	Active         *bool              `db:"active"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        string             `db:"after_id"`
	RowLimit       int32              `db:"row_limit"`
}

type ListDelegationDetailsRow struct {
	ID            string             `db:"id"`
	ZoneBindingID string             `db:"zone_binding_id"`
	GranteeKind   string             `db:"grantee_kind"`
	GranteeID     string             `db:"grantee_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	RevokedAt     pgtype.Timestamptz `db:"revoked_at"`
}

func (q *Queries) ListDelegationDetails(ctx context.Context, arg ListDelegationDetailsParams) ([]ListDelegationDetailsRow, error) {
	rows, err := q.db.Query(ctx, listDelegationDetails,
		arg.ZoneBindingID,
		arg.GranteeID,
		arg.Active,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDelegationDetailsRow{}
	for rows.Next() {
		var i ListDelegationDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.ZoneBindingID,
			&i.GranteeKind,
			&i.GranteeID,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelegationRecordTypesByIDs = `-- name: ListDelegationRecordTypesByIDs :many
SELECT delegation_id, record_type
FROM delegation_record_types
WHERE delegation_id = ANY($1::uuid[])
ORDER BY delegation_id, record_type
`

func (q *Queries) ListDelegationRecordTypesByIDs(ctx context.Context, delegationIds []string) ([]DelegationRecordType, error) {
	rows, err := q.db.Query(ctx, listDelegationRecordTypesByIDs, delegationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DelegationRecordType{}
	for rows.Next() {
		var i DelegationRecordType
		if err := rows.Scan(&i.DelegationID, &i.RecordType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDelegationSelectorsByIDs = `-- name: ListDelegationSelectorsByIDs :many
SELECT delegation_id, position, kind, selector, sql_like_pattern
FROM delegation_selectors
WHERE delegation_id = ANY($1::uuid[])
ORDER BY delegation_id, position
`

func (q *Queries) ListDelegationSelectorsByIDs(ctx context.Context, delegationIds []string) ([]DelegationSelector, error) {
	rows, err := q.db.Query(ctx, listDelegationSelectorsByIDs, delegationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DelegationSelector{}
	for rows.Next() {
		var i DelegationSelector
		if err := rows.Scan(
			&i.DelegationID,
			&i.Position,
			&i.Kind,
			&i.Selector,
			&i.SQLLikePattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEffectiveDelegationDetails = `-- name: ListEffectiveDelegationDetails :many
SELECT d.id, d.zone_binding_id, binding.powerdns_zone_id, binding.zone_name,
       CASE WHEN d.grantee_identity_id IS NOT NULL THEN 'identity' ELSE 'group' END::text AS grantee_kind,
       COALESCE(d.grantee_identity_id, d.grantee_group_id)::text AS grantee_id,
       d.created_at, d.revoked_at
FROM delegations AS d
JOIN zone_bindings AS binding
  ON binding.id = d.zone_binding_id
 AND binding.retired_at IS NULL
WHERE d.revoked_at IS NULL
  AND (
      d.grantee_identity_id = NULLIF($1::text, '')::uuid
      OR EXISTS (
          SELECT 1
          FROM group_memberships AS membership
          JOIN groups AS member_group
            ON member_group.id = membership.group_id
           AND member_group.enabled = true
          WHERE membership.identity_id = NULLIF($1::text, '')::uuid
            AND membership.group_id = d.grantee_group_id
      )
  )
  AND (
      $2::timestamptz IS NULL
      OR (d.created_at, d.id) < (
          $2,
          NULLIF($3::text, '')::uuid
      )
  )
ORDER BY d.created_at DESC, d.id DESC
LIMIT $4
`

type ListEffectiveDelegationDetailsParams struct {
	IdentityID     string             `db:"identity_id"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        string             `db:"after_id"`
	RowLimit       int32              `db:"row_limit"`
}

type ListEffectiveDelegationDetailsRow struct {
	ID             string             `db:"id"`
	ZoneBindingID  string             `db:"zone_binding_id"`
	PowerDNSZoneID string             `db:"powerdns_zone_id"`
	ZoneName       string             `db:"zone_name"`
	GranteeKind    string             `db:"grantee_kind"`
	GranteeID      string             `db:"grantee_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	RevokedAt      pgtype.Timestamptz `db:"revoked_at"`
}

func (q *Queries) ListEffectiveDelegationDetails(ctx context.Context, arg ListEffectiveDelegationDetailsParams) ([]ListEffectiveDelegationDetailsRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveDelegationDetails,
		arg.IdentityID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEffectiveDelegationDetailsRow{}
	for rows.Next() {
		var i ListEffectiveDelegationDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.ZoneBindingID,
			&i.PowerDNSZoneID,
			&i.ZoneName,
			&i.GranteeKind,
			&i.GranteeID,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT i.id, i.kind, i.handle, i.display_name, i.enabled, i.is_operator,
       i.created_at, i.updated_at
FROM group_memberships AS m
JOIN identities AS i ON i.id = m.identity_id
WHERE m.group_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (i.created_at, i.id) < (
          $2,
          NULLIF($3::text, '')::uuid
      )
  )
ORDER BY i.created_at DESC, i.id DESC
LIMIT $4
`

type ListGroupMembersParams struct {
	GroupID        string             `db:"group_id"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        string             `db:"after_id"`
	RowLimit       int32              `db:"row_limit"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listGroupMembers,
		arg.GroupID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Handle,
			&i.DisplayName,
			&i.Enabled,
			&i.IsOperator,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, handle, display_name, enabled, created_at, updated_at
FROM groups
WHERE ($1::boolean IS NULL OR enabled = $1)
  AND ($2::text IS NULL OR handle = $2)
  AND (
      $3::timestamptz IS NULL
      OR (created_at, id) < (
          $3,
          NULLIF($4::text, '')::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListGroupsParams struct {
	Enabled        *bool              `db:"enabled"`
	Handle         *string            `db:"handle"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        string             `db:"after_id"`
	RowLimit       int32              `db:"row_limit"`
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups,
		arg.Enabled,
		arg.Handle,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.DisplayName,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, kind, handle, display_name, enabled, is_operator, created_at, updated_at
FROM identities
WHERE ($1::text IS NULL OR kind = $1)
  AND ($2::boolean IS NULL OR enabled = $2)
  AND ($3::boolean IS NULL OR is_operator = $3)
  AND ($4::text IS NULL OR handle = $4)
  AND (
      $5::timestamptz IS NULL
      OR (created_at, id) < (
          $5,
          NULLIF($6::text, '')::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $7
`

type ListIdentitiesParams struct {
	Kind           *string            `db:"kind"`
	Enabled        *bool              `db:"enabled"`
	IsOperator     *bool              `db:"is_operator"`
	Handle         *string            `db:"handle"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        string             `db:"after_id"`
	RowLimit       int32              `db:"row_limit"`
}

func (q *Queries) ListIdentities(ctx context.Context, arg ListIdentitiesParams) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentities,
		arg.Kind,
		arg.Enabled,
		arg.IsOperator,
		arg.Handle,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Handle,
			&i.DisplayName,
			&i.Enabled,
			&i.IsOperator,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityGroups = `-- name: ListIdentityGroups :many
SELECT g.id, g.handle, g.display_name, g.enabled, g.created_at, g.updated_at
FROM group_memberships AS m
JOIN groups AS g ON g.id = m.group_id
WHERE m.identity_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (g.created_at, g.id) < (
          $2,
          NULLIF($3::text, '')::uuid
      )
  )
ORDER BY g.created_at DESC, g.id DESC
LIMIT $4
`

type ListIdentityGroupsParams struct {
	IdentityID     string             `db:"identity_id"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        string             `db:"after_id"`
	RowLimit       int32              `db:"row_limit"`
}

func (q *Queries) ListIdentityGroups(ctx context.Context, arg ListIdentityGroupsParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, listIdentityGroups,
		arg.IdentityID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.DisplayName,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZoneBindings = `-- name: ListZoneBindings :many
SELECT id, generation, upstream, powerdns_zone_id, zone_name,
       created_by_identity_id, retired_by_identity_id, created_at, retired_at
FROM zone_bindings
WHERE (NULLIF($1::text, '') IS NULL
       OR $1 = 'active' AND retired_at IS NULL
       OR $1 = 'retired' AND retired_at IS NOT NULL)
  AND (NULLIF($2::text, '') IS NULL OR zone_name = $2)
  AND (
      $3::timestamptz IS NULL
      OR (created_at, id) < (
          $3,
          NULLIF($4::text, '')::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListZoneBindingsParams struct {
	Status         string             `db:"status"`
	ZoneName       string             `db:"zone_name"`
	AfterCreatedAt pgtype.Timestamptz `db:"after_created_at"`
	AfterID        string             `db:"after_id"`
	RowLimit       int32              `db:"row_limit"`
}

func (q *Queries) ListZoneBindings(ctx context.Context, arg ListZoneBindingsParams) ([]ZoneBinding, error) {
	rows, err := q.db.Query(ctx, listZoneBindings,
		arg.Status,
		arg.ZoneName,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZoneBinding{}
	for rows.Next() {
		var i ZoneBinding
		if err := rows.Scan(
			&i.ID,
			&i.Generation,
			&i.Upstream,
			&i.PowerDNSZoneID,
			&i.ZoneName,
			&i.CreatedByIdentityID,
			&i.RetiredByIdentityID,
			&i.CreatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOperatorGuard = `-- name: LockOperatorGuard :one
SELECT singleton
FROM operator_guard
WHERE singleton = true
FOR UPDATE
`

func (q *Queries) LockOperatorGuard(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockOperatorGuard)
	var singleton bool
	err := row.Scan(&singleton)
	return singleton, err
}

const lockZoneBindingKey = `-- name: LockZoneBindingKey :exec
SELECT pg_advisory_xact_lock(1145130580, hashtext($1))
`

func (q *Queries) LockZoneBindingKey(ctx context.Context, hashtext string) error {
	_, err := q.db.Exec(ctx, lockZoneBindingKey, hashtext)
	return err
}

const nextZoneBindingGeneration = `-- name: NextZoneBindingGeneration :one
SELECT (COALESCE(max(generation), 0) + 1)::bigint
FROM zone_bindings
WHERE upstream = $1 AND zone_name = $2
`

type NextZoneBindingGenerationParams struct {
	Upstream string `db:"upstream"`
	ZoneName string `db:"zone_name"`
}

func (q *Queries) NextZoneBindingGeneration(ctx context.Context, arg NextZoneBindingGenerationParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextZoneBindingGeneration, arg.Upstream, arg.ZoneName)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const removeGroupMembership = `-- name: RemoveGroupMembership :execrows
DELETE FROM group_memberships
WHERE group_id = $1 AND identity_id = $2
`

type RemoveGroupMembershipParams struct {
	GroupID    string `db:"group_id"`
	IdentityID string `db:"identity_id"`
}

func (q *Queries) RemoveGroupMembership(ctx context.Context, arg RemoveGroupMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGroupMembership, arg.GroupID, arg.IdentityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireZoneBinding = `-- name: RetireZoneBinding :one
UPDATE zone_bindings
SET retired_at = statement_timestamp(),
    retired_by_identity_id = NULLIF($1::text, '')::uuid
WHERE id = $2 AND retired_at IS NULL
RETURNING id, generation, upstream, powerdns_zone_id, zone_name,
          created_by_identity_id, retired_by_identity_id, created_at, retired_at
`

type RetireZoneBindingParams struct {
	RetiredByIdentityID string `db:"retired_by_identity_id"`
	ID                  string `db:"id"`
}

func (q *Queries) RetireZoneBinding(ctx context.Context, arg RetireZoneBindingParams) (ZoneBinding, error) {
	row := q.db.QueryRow(ctx, retireZoneBinding, arg.RetiredByIdentityID, arg.ID)
	var i ZoneBinding
	err := row.Scan(
		&i.ID,
		&i.Generation,
		&i.Upstream,
		&i.PowerDNSZoneID,
		&i.ZoneName,
		&i.CreatedByIdentityID,
		&i.RetiredByIdentityID,
		&i.CreatedAt,
		&i.RetiredAt,
	)
	return i, err
}

const revokeAPIToken = `-- name: RevokeAPIToken :one
UPDATE api_tokens
SET revoked_at = statement_timestamp()
WHERE identity_id = $1 AND id = $2 AND revoked_at IS NULL
RETURNING id, identity_id, label, expires_at, revoked_at, created_at,
          'revoked'::text AS status
`

type RevokeAPITokenParams struct {
	IdentityID string `db:"identity_id"`
	ID         string `db:"id"`
}

type RevokeAPITokenRow struct {
	ID         string             `db:"id"`
	IdentityID string             `db:"identity_id"`
	Label      string             `db:"label"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	Status     string             `db:"status"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (RevokeAPITokenRow, error) {
	row := q.db.QueryRow(ctx, revokeAPIToken, arg.IdentityID, arg.ID)
	var i RevokeAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.IdentityID,
		&i.Label,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const revokeAllActiveAPITokens = `-- name: RevokeAllActiveAPITokens :execrows
UPDATE api_tokens
SET revoked_at = statement_timestamp()
WHERE revoked_at IS NULL
`

func (q *Queries) RevokeAllActiveAPITokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllActiveAPITokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeDelegation = `-- name: RevokeDelegation :one
UPDATE delegations
SET revoked_at = statement_timestamp(),
    revoked_by_identity_id = NULLIF($2::text, '')::uuid
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, zone_binding_id, grantee_identity_id, grantee_group_id,
          created_by_identity_id, revoked_by_identity_id, created_at, revoked_at
`

type RevokeDelegationParams struct {
	ID                  string `db:"id"`
	RevokedByIdentityID string `db:"revoked_by_identity_id"`
}

func (q *Queries) RevokeDelegation(ctx context.Context, arg RevokeDelegationParams) (Delegation, error) {
	row := q.db.QueryRow(ctx, revokeDelegation, arg.ID, arg.RevokedByIdentityID)
	var i Delegation
	err := row.Scan(
		&i.ID,
		&i.ZoneBindingID,
		&i.GranteeIdentityID,
		&i.GranteeGroupID,
		&i.CreatedByIdentityID,
		&i.RevokedByIdentityID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeDelegationsForZoneDeletion = `-- name: RevokeDelegationsForZoneDeletion :many
UPDATE delegations
SET revoked_at = statement_timestamp(),
    revoked_by_identity_id = NULLIF($1::text, '')::uuid
WHERE zone_binding_id = $2
  AND revoked_at IS NULL
RETURNING id
`

type RevokeDelegationsForZoneDeletionParams struct {
	RevokedByIdentityID string `db:"revoked_by_identity_id"`
	ZoneBindingID       string `db:"zone_binding_id"`
}

func (q *Queries) RevokeDelegationsForZoneDeletion(ctx context.Context, arg RevokeDelegationsForZoneDeletionParams) ([]string, error) {
	rows, err := q.db.Query(ctx, revokeDelegationsForZoneDeletion, arg.RevokedByIdentityID, arg.ZoneBindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET display_name = $2,
    enabled = $3,
    updated_at = statement_timestamp()
WHERE id = $1
RETURNING id, handle, display_name, enabled, created_at, updated_at
`

type UpdateGroupParams struct {
	ID          string  `db:"id"`
	DisplayName *string `db:"display_name"`
	Enabled     bool    `db:"enabled"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.DisplayName, arg.Enabled)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentity = `-- name: UpdateIdentity :one
UPDATE identities
SET display_name = $2,
    enabled = $3,
    is_operator = $4,
    updated_at = statement_timestamp()
WHERE id = $1
RETURNING id, kind, handle, display_name, enabled, is_operator, created_at, updated_at
`

type UpdateIdentityParams struct {
	ID          string  `db:"id"`
	DisplayName *string `db:"display_name"`
	Enabled     bool    `db:"enabled"`
	IsOperator  bool    `db:"is_operator"`
}

func (q *Queries) UpdateIdentity(ctx context.Context, arg UpdateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, updateIdentity,
		arg.ID,
		arg.DisplayName,
		arg.Enabled,
		arg.IsOperator,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Handle,
		&i.DisplayName,
		&i.Enabled,
		&i.IsOperator,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const zoneBindingHistoryExists = `-- name: ZoneBindingHistoryExists :one
SELECT EXISTS (
    SELECT 1
    FROM zone_bindings
    WHERE upstream = $1
      AND (powerdns_zone_id = $2 OR zone_name = $3)
)
`

type ZoneBindingHistoryExistsParams struct {
	Upstream       string `db:"upstream"`
	PowerDNSZoneID string `db:"powerdns_zone_id"`
	ZoneName       string `db:"zone_name"`
}

func (q *Queries) ZoneBindingHistoryExists(ctx context.Context, arg ZoneBindingHistoryExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, zoneBindingHistoryExists, arg.Upstream, arg.PowerDNSZoneID, arg.ZoneName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
